### ISSUE TITLE
Prefer lowercase variables

### ISSUE THREAD

**Issue by sarahsturgeon** [sarahsturgeon/cfc_factions_3#17]
In most cases, lowercase variable names are preferred unless they're constants, or unless they're properties/functions of an object.

In this case, I'm focused on things like this: https://github.com/brandonsturgeon/cfc_factions_3/blob/master/lua/cfcfactions/core/sv/sv_factionmanagment.lua#L271

`K` should be a lowercase `k` (and should be renamed as per: https://github.com/brandonsturgeon/cfc_factions_3/issues/14)

**Comment by overlordbleck** [comment]
https://github.com/brandonsturgeon/cfc_factions_3/pull/22
