### ISSUE TITLE
Parentheses on conditionals that don't need them should be removed

### ISSUE THREAD

**Issue by justinmuskopf** [sarahsturgeon/cfc_factions_3#19]
Par Exemple:
https://github.com/brandonsturgeon/cfc_factions_3/blob/master/lua/cfcfactions/core/sv/sv_factions.lua#L43-L82

The first one should look something like this:
```lua
if type(factionOwner) ~= "Player" then
    cfcFactions:SendNotifcation(cfcFactions.ErrorMessages[1], 1, nil)
    return
end
```

**Comment by overlordbleck** [comment]
https://github.com/brandonsturgeon/cfc_factions_3/pull/23
