### ISSUE TITLE
Refactor error messages

### ISSUE THREAD

**Issue by sarahsturgeon** [sarahsturgeon/cfc_factions_3#3]
https://github.com/brandonsturgeon/cfc_factions_3/blob/master/lua/cfcfactions/core/sh/sh_sharedutils.lua#L21-L54

Instead of integer indices, they should be string indices.

e.g:

```lua
ply:ChatPrint(errorMessages[21])
```

becomes

```lua
ply:ChatPrint(errorMessages["player-is-tester"])
```

**Comment by overlordbleck** [comment]
Resolved in https://github.com/brandonsturgeon/cfc_factions_3/pull/20
