### ISSUE TITLE
Populate faction menu

### ISSUE THREAD

**Issue by plally** [sarahsturgeon/cfc_factions_3#34]
faction data should be sent to the client and the faction menu should display real factions. (the menu currently displays 10 randomly created factions)

**Comment by ghost** [comment]
Removed some debug left over debug code for this. 0124fe2e337d2dcad01be26469098ae9a1c0a20c

**Comment by ghost** [comment]
Needs to be finished but a lot of clean up has occurred f4f8f41393e8ecc0a07c08921f3690b15767328e

Finishing some remaining code to add to Faction's View

**Comment by ghost** [comment]
This should be finished now. Was finished sometime ago but forgot to update on progress
