### ISSUE TITLE
Ensure there are spaces inside of parens

### ISSUE THREAD

**Issue by sarahsturgeon** [sarahsturgeon/cfc_factions_3#5]
e.g: https://github.com/brandonsturgeon/cfc_factions_3/blob/master/lua/cfcfactions/core/sv/sv_factions.lua#L43

All parenthesis should have spaces inside of them.

```lua
if (not type(factionOwner) == "Player") then
```
becomes
```lua
if ( not type(factionOwner) == "Player" ) then
```

**Comment by justinmuskopf** [comment]
https://github.com/brandonsturgeon/cfc_factions_3/pull/45
