### ISSUE TITLE
Standardize whitespace

### ISSUE THREAD

**Issue by sarahsturgeon** [sarahsturgeon/cfc_factions_3#6]
e.g: https://github.com/brandonsturgeon/cfc_factions_3/blob/master/lua/cfcfactions/core/sv/sv_factions.lua#L83-L88

Whitespace should often be no more than two lines to separate sections. One line of whitespace is preferred.

**Comment by overlordbleck** [comment]
https://github.com/brandonsturgeon/cfc_factions_3/pull/25 addressed this issue
